[server] # flask app settings in app.run()
debug = true
host = '127.0.0.1'
port = 5000

[model]
llm_prompt = """
Give me a prompt of the subject and surrounding of the Chinese character(s) %s.
The subject and each surrounding should be a few English words.
You should focus on the thing that the character represents, and the surrounding should be something about the composition or the structure of the thing that the character represents.
Don't be so descriptive. A pattern of adj. + n. is enough, and the noun should be something concrete, not abstract.
Your answer should be json format like this:
{
    "sub_prompt": "Your Subject",
    "surr_prompt": "Your Surrounding1, Your Surrounding2,..." // 5-10 items
}
Example: If I give you the character 蔷, your answer should be:
{
    "sub_prompt": "a red rose flower blooming ",
    "surr_prompt": "brown vignette, leaf, slender branch, thorns in a romantic atmosphere "
}
Your answer should include nothing but json. 
"""