[server]        # flask app settings in app.run()
debug = true
host = '127.0.0.1'
port = 5000

[model]
device="cuda"    #cpu or cuda
dtype="float16" #float16 by defaut

[model.name]    #path of the models
controlnet_scribble="./model/model_weights/sd-controlnet-scribble"
controlnet_seg="./model/model_weights/sd-controlnet-seg"
stable_diffusion="./model/model_weights/stable-diffusion-v1-5"
sd_depth="stabilityai/stable-diffusion-2-depth"

[model.inference]
num_inference_steps=50
guidance_scale=15
controlnet_conditioning_scale=1.2
weights=0.85
addl_controlnet_conditioning_scale=1.9
callback_steps=1

[model.typo]
guidance_scale=35
strength=0.85
gen_num=5

[model.LLM]
LLM_base_url="https://api.deepseek.com"
model_name="deepseek-chat"
cache_path="./temp/LLM_cache.json"

[model.prompts]
typo_prompt_template="a black and white drawing of {sub_prompt}, {positive_prompt}" 
positive_prompt = "no humans, no vignetting, complete, beautiful, clear,  elegant, artistic, (easy background), (plain background), (simple background), (clean background), easy layout, plain layout, simple layout, one, individual, sole, isolated, solitary, detached, alone, subjectival, planar, orderly, negative space "
negative_prompt = "(deformed), vignetting, Camera dark angle, (bad), (ugly), lousy anatomy, worst quality, low quality, jpeg artifacts, uplicate, morbid, mutilated, extra things, cut off, deformities, bad anatomy, bad proportions, deformed, blurry, stereoscopic, cluttered background, complex background, cluttered layout, complex layout, multiple, poly"
llm_prompt = """
Give me a prompt of the subject and surrounding of the Chinese character(s) %s.
The subject and each surrounding should be a few English words.
You should focus on the thing that the character represents, and the surrounding should be something about the composition or the structure of the thing that the character represents.
Don't be so descriptive. A pattern of adj. + n. is enough, and the noun should be something concrete, not abstract.
Your answer should be json format like this:
{
    "sub_prompt": "Your Subject",
    "surr_prompt": ["Your Surrounding1", "Your Surrounding2"] // 5-10 items
}
Example: If I give you the character 蔷, your answer should be:
{
    "sub_prompt": "a red rose flower blooming ",
    "surr_prompt": ["brown vignette", "leaf", "slender branch", "thorns in a romantic atmosphere"]
}
Your answer should include nothing but json. 
"""

[lora]
path = "./model/loras"
ext = ['.safetensors', '.bin', '.pt', '.pth']